feat: (fe) 사이클 상세 조회 페이지 UI 구현
woowacourse-teams/2022-smody pull request #179
Opened 2022-08-02 11:12 UTC by ronci

2022-08-02 16:13 UTC, wonsss commented on frontend/src/components/CycleDetailList/index.tsx
> +        return <CycleDetailItem key={cycleDetail.progressTime} {...cycleDetail} />;
key로 progressTime을 주셨네요! 더 나은 key는 없을까요? progressTime이 key로 적절하다고 생각하신 이유도 알려주시면 감사하겠습니다. :)

2022-08-02 16:16 UTC, wonsss commented on frontend/src/components/CycleDetailItem/index.tsx
> +const CycleImg = styled.div<CycleImgProps>`
img 태그 대신 div 태그를 사용하신 이유가 궁금해요!

2022-08-02 16:18 UTC, wonsss commented on frontend/src/pages/CycleDetailPage/index.tsx
> +      </TitleWrapper>
이 부분이 계속 자주 쓰여서, 빅터랑 제가 `Title` 이라는 컴포넌트를 만들어 분리했는데, 머지되면 같이 수정하면 좋을 것 같아요!

2022-08-02 16:32 UTC, wonsss requested changes

2022-08-02 16:32 UTC, wonsss commented on frontend/src/utils/index.ts
> +};
'2022-07-01T17:00:00'과 같은 dateString을 인자로 받아서 parsing하는 함수는 아래와 같이 범용성 있게 만들면 어떨까요? 앞으로 사용자에게 보여줄 date 형식이 달라질 가능성도 있을 것 같아서요. :)

```ts
const parseDate = (dateString: string) => {
    const parsedDate = new Date(Date.parse(dateString));
    const year = parsedDate.getFullYear();
    const month = parsedDate.getMonth() + 1;
    const date = parsedDate.getDate();
    const hours = parsedDate.getHours();
    const minutes = parsedDate.getMinutes();

    return { year, month, date, hours, minutes }
}

// 사용
parseDate('2022-07-01T17:00:00')  // {year: 2022, month: 7, date: 1, hours: 17, minutes: 0}
```

2022-08-03 04:03 UTC, ronci commented on frontend/src/pages/ChallengeDetailPage/index.tsx
> +          style={makeCursorPointer}
- 좋습니다!
- cursorPointer로 수정했습니다!
- 넵! 현재 constants 파일에서 style을 분리할 파일이 없어서 style.ts을 만들었습니다

2022-08-03 04:15 UTC, ronci commented on frontend/src/utils/index.ts
> +};
좋은 방법이네요! 수정했습니다!
그러면 parseDate를 사용하고 실제 코드에서 각 format에 맞춰서 출력하면 좋을 것 같네요!

2022-08-03 04:29 UTC, ronci commented on frontend/src/components/CycleDetailList/index.tsx
> +        return <CycleDetailItem key={cycleDetail.progressTime} {...cycleDetail} />;
사이클 내부에서는 progressTime이 고유한 값이기 때문에 다음과 같이 정했습니다!

2022-08-03 04:30 UTC, ronci commented on frontend/src/components/CycleDetailItem/index.tsx
> +const CycleImg = styled.div<CycleImgProps>`
css사용하기 편해서 다음과 같이 사용해봤는데 후에 수정해봐도 좋을 것 같습니다!

2022-08-03 04:30 UTC, ronci commented on frontend/src/pages/CycleDetailPage/index.tsx
> +      </TitleWrapper>
네 좋습니다!

2022-08-03 04:31 UTC, wonsss approved these changes
고생하셨습니다! 좋아요.

2022-08-03 05:15 UTC, merged