feat: (fe) 알림 구독 토글의 disabled 이슈를 해결
woowacourse-teams/2022-smody pull request #276
Opened 2022-08-13 06:04 UTC by wonsss

close #275

2022-08-14 11:51 UTC, woose28 requested changes
실행을 시켜보고 싶었지만, 아쉽게 에러가 발생하네요..!
코멘트를 남겼으니 확인부탁드려요~

2022-08-14 11:51 UTC, woose28 commented on frontend/src/index.tsx
> +  const { mockServiceWorker } = require('./mocks/browser');
현재 해당 브랜치를 development mode로 실행시켰을 때(yarn run start:dev) 실행이 안 되고 있습니다..!

발생되는 에러는 아래와 같습니다.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/52148907/184534350-7c6b3c26-f65b-45fa-915c-295858274a5a.png">

아마도 `./mocks/browser`에서 worker를 export하고 있어서 그런 거 같아요!
한 번 확인 부탁드릴게요~

2022-08-14 11:51 UTC, woose28 commented on frontend/src/index.tsx
> -  registerServiceWorker();
함수를 다른 파일로 분리해주셨네요👍
덕분에 index.tsx가 더 깔끔해진 거 같아요~

2022-08-14 11:51 UTC, woose28 commented on frontend/src/push/registerPushServiceWorker.ts
> +  'serviceWorker' in navigator && 'Notification' in window && 'PushManager' in window;
매개 변수로 받는 값이 존재하진 않네요!
이런 경우에는 함수 대신 변수를 사용하는 건 어떨까요?

2022-08-14 11:51 UTC, woose28 commented on frontend/src/push/registerPushServiceWorker.ts
> +    registration = await navigator.serviceWorker.register('pushServiceWorker.js');
`pushServiceWorker.js` 파일은 어디에 존재하는 파일인지 알 수 있을까요?

2022-08-14 11:53 UTC, wonsss commented on frontend/src/index.tsx
> +  const { mockServiceWorker } = require('./mocks/browser');
yarn run start:local 에서도 실행이 되지 않을까요?

2022-08-14 14:10 UTC, wonsss commented on frontend/src/index.tsx
> -  registerServiceWorker();
감사합니다!

2022-08-14 16:04 UTC, wonsss commented on frontend/src/push/registerPushServiceWorker.ts
> +  'serviceWorker' in navigator && 'Notification' in window && 'PushManager' in window;
그렇네요! 수정했어요 👍

2022-08-14 16:05 UTC, wonsss commented on frontend/src/push/registerPushServiceWorker.ts
> +    registration = await navigator.serviceWorker.register('pushServiceWorker.js');
파일명은 수정하지 않았네요! 파일명을 수정했고 해당 파일은 public 폴더 안에 있어요.

2022-08-15 02:15 UTC, woose28 commented on frontend/src/index.tsx
> +  const { mockServiceWorker } = require('./mocks/browser');
> 앱모드 환경변수 관리
덕분에 사용처에서 훨씬 코드가 간결해졌네요👍

2022-08-15 02:23 UTC, woose28 approved these changes
정상 실행되는 거 확인했습니다~~
수정 요청 사항을 빠르게 반영해주셨네요💯
고생 많으셨어요!

2022-08-15 02:48 UTC, merged