feat: (fe) 나의 알림 조회 및 읽은 알림 삭제 기능 UI와 API 연결 로직 작성
woowacourse-teams/2022-smody pull request #291
Opened 2022-08-14 13:06 UTC by wonsss

close #290

relate #289  백엔드 해당 API 작업 브랜치를 pull 받아서 로컬에서 테스트 완료함

## after
![알림 조회 및 삭제](https://user-images.githubusercontent.com/59413128/184538295-0e044282-800e-4d33-a9be-24610c05c899.gif)

2022-08-15 04:32 UTC, ronci requested changes
알람 조회기능 벌써 부터 기대되네요!
코드 구현하느라 수고하셨어요!

코멘트 몇 개 남겼는데 확인 한 번 부탁드려요!

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/Dropdown/index.tsx
> +  const onSelectMenu: MouseEventHandler<HTMLUListElement> = () => {
`MouseEventHandler<HTMLUListElement>` type이 필요할까요??

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/Dropdown/index.tsx
>      setDropdownToggled(true);
이런 로직들은 custom hook으로 분리해도 좋을 것 같아요!

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/NotificationMessage/index.tsx
> +              {parseTime(pushTime).year}년 {parseTime(pushTime).month}월{' '}
react에서 빈공간은 `&nbsp;` 이걸 이용해서 넣을 수도 있어요!

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/NotificationMessage/index.tsx
> +              {parseTime(pushTime).hours}시 {parseTime(pushTime).minutes}분
계속 parseTime을 쓰는 것 보다 한 번에 구조분해할당으로 가져와서 바로 year, date, hours를 쓰는 건 어떨까요??

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/NotificationMessage/index.tsx
> +        color: rgb(246, 221, 255);
`filter: brightness() `를 사용해보는 건 어떨까요?

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/NotificationMessage/index.tsx
> +
바로 Text로 사용해도 되지않을까요??

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/NotificationMessage/useNotificationMessage.ts
> +      console.log('딜리트');
console.log 제거해주세요!

2022-08-15 04:32 UTC, ronci commented on frontend/src/components/NotificationMessage/useNotificationMessage.ts
> +      navigate(`/search`);
이것도 path.ts에 상수화한 값으로 바꾸면 좋을 것 같아요!

2022-08-15 04:32 UTC, ronci commented on frontend/src/hooks/useSubscribe.ts
>        console.log('4-Push unsubscribed:', userSubscription, result);
console.log 제거해주세요!

2022-08-15 06:34 UTC, wonsss commented on frontend/public/serviceWorker.js
> +    path = `/profile`;
맞네요!수정할게요 감사합니다

2022-08-15 06:36 UTC, wonsss commented on frontend/public/serviceWorker.js
> +    console.log('hi');
넵!!

2022-08-15 06:38 UTC, wonsss commented on frontend/src/components/Dropdown/index.tsx
> +  const onSelectMenu: MouseEventHandler<HTMLUListElement> = () => {
event를 받지 않아서 이 함수는 필요없겠네요! 수정했어요

2022-08-15 06:42 UTC, wonsss commented on frontend/src/components/Dropdown/index.tsx
>      setDropdownToggled(true);
맞네요! 우리 컨벤션대로 수정했어요

2022-08-15 06:47 UTC, wonsss commented on frontend/src/components/NotificationMessage/index.tsx
> +              {parseTime(pushTime).hours}시 {parseTime(pushTime).minutes}분
넵 아래처럼 수정했어요!

```typescript
  const formatTime = (time: string) => {
    const { year, month, date, hours, minutes } = parseTime(time);
    return `${year}년 ${month}월 ${date}일 ${hours}:${minutes}`;
  };
```

2022-08-15 06:47 UTC, wonsss commented on frontend/src/components/NotificationMessage/index.tsx
> +              {parseTime(pushTime).year}년 {parseTime(pushTime).month}월{' '}
꿀팁 감사해요

2022-08-15 06:48 UTC, wonsss commented on frontend/src/components/NotificationMessage/index.tsx
> +
스타일이 바뀔 여지가 있어서 일단 남겨뒀어요

2022-08-15 06:48 UTC, wonsss commented on frontend/src/components/NotificationMessage/useNotificationMessage.ts
> +      console.log('딜리트');
넵!

2022-08-15 06:50 UTC, wonsss commented on frontend/src/components/NotificationMessage/useNotificationMessage.ts
> +      navigate(`/search`);
넵! 수정했어요

2022-08-15 06:52 UTC, wonsss commented on frontend/src/hooks/useSubscribe.ts
>        console.log('4-Push unsubscribed:', userSubscription, result);
넵 수정했어요

2022-08-15 07:32 UTC, ronci commented on frontend/src/components/NotificationMessage/index.tsx
> +              {parseTime(pushTime).year}년 {parseTime(pushTime).month}월{' '}
앗 근데  현재 방법이 더 좋은 것 같아요!
방금 찾아보고 왔는데,  `&nbsp;`의 경우 구 버전의 React는 v14 이전의 모든 버전이 태그 안에 개행 문자가 있으면 자동으로 `<span> </span>`를 삽입하기 때문에 의도하지 않은 부작용이 있을 수도 있다고 하네요!
[JSX에 공백을 추가 할 때 모범 사례](https://www.wake-up-neo.net/ko/javascript/jsx%EC%97%90-%EA%B3%B5%EB%B0%B1%EC%9D%84-%EC%B6%94%EA%B0%80-%ED%95%A0-%EB%95%8C-%EB%AA%A8%EB%B2%94-%EC%82%AC%EB%A1%80/827531416/amp/)

2022-08-16 07:31 UTC, ronci approved these changes
고치느라 수고하셨어요! Approve할께요!

2022-08-16 09:01 UTC, merged