fix: (fe) 피드 상세 페이지에서 챌린지 이름 관련 이슈 해결
woowacourse-teams/2022-smody pull request #385
Opened 2022-09-06 08:03 UTC by woose28

close #380 

# 상세 페이지에서는 관련 챌린지로 이동이 안됨
## 해결 방안
FeedItem의 ChallengeName 스타일드 컴포넌트에 `pointer-events: auto` 스타일 추가했습니다. 이로인해 부모의 `pointer-events` 값에 관계없이 ChallengeName은 포인터 이벤트의 대상이 될 수 있습니다.

## 참고 자료
[MDN pointer-events](https://developer.mozilla.org/ko/docs/Web/CSS/pointer-events)

<br>

# 상세 페이지에서는 챌린지의 이름이 전체가 나와도 좋을 것 같음
## 에러 상황
### 피드 페이지
<img width="585" alt="피드 페이지 - 챌린지 이름 요약해서 보여줌" src="https://user-images.githubusercontent.com/52148907/188579852-e1c849d8-74a9-42cd-b721-69965a412271.png">

### 피드 상세 보기 페이지
<img width="585" alt="피드 상세 보기 페이지 - 피드 챌린지 이름  전체 보여줌" src="https://user-images.githubusercontent.com/52148907/188579861-cf4885ee-6b32-4da3-9560-c087a8010ac3.png">

`상쾌한 하루의 시작, 미라클 모닝!` 챌린지 이름을 피드 페이지에서는 요약해서 보이고, 피드 상세 페이지에서는 전체 이름을 보여주도록 구현했습니다.

## 해결 방안
FeedItem 컴포넌트에 isShowBriefChallengeName Props를 추가했습니다. isShowBriefChallengeName Props에 따라 챌린지 이름의 요약 여부를 결정하도록 구현했습니다.

2022-09-06 08:15 UTC, wonsss approved these changes
good!

2022-09-06 08:15 UTC, wonsss commented on frontend/src/components/FeedItem/index.tsx
> +  pointer-events: auto;
pointer-events의 기본값이 auto 인 것 같은데, 명시적으로 설정해주신 이유가 있으실까요?

2022-09-06 08:15 UTC, wonsss commented on frontend/src/pages/FeedDetailPage/index.tsx
> +      <FeedItem isClickable={false} isShowBriefChallengeName={false} {...feedData.data} />
이름 요약 여부를 속성을 통해 정할 수 있으니 편리하네요!

2022-09-06 08:15 UTC, wonsss commented on frontend/src/components/FeedItem/index.tsx
> +            : challengeName}
오 좋네요. 축약 기능이 켜져있을 때, 9글자 이하여서 굳이 축약할 필요도 없고 `...`도 붙일 필요가 없을 때까지 고려하여 섬세히 작성하셨네요

2022-09-07 06:04 UTC, ronci requested changes
빅터 수고하셨어요! review하나 달았는 데 한 번 고려해봐주시면 좋을 것 같아요!

2022-09-07 06:04 UTC, ronci commented on frontend/src/components/FeedItem/index.tsx
> +          {isShowBriefChallengeName && challengeName.length > 9
이 로직 자체를 custom hook자체로 분리해서 보여지는 challengeName을 바로 가져올 수 있을 것 같아요!

2022-09-07 06:27 UTC, woose28 commented on frontend/src/components/FeedItem/index.tsx
> +  pointer-events: auto;
부모 컴포넌트의 pointer-events의 값에 상관없이 해당 컴포넌트가 항상 이벤트의 대상이 되게 하기 위해서 명시적으로 auto 값을 사용했습니다.

해당 스타일 속성은 상속이 되는 속성이기 때문에 자식 컴포넌트에서 값을 명시적으로 사용하지 않으면, 부모 태그에서 지정한 값이 적용됩니다!

[MDN pointer-events 형식](https://developer.mozilla.org/ko/docs/Web/CSS/pointer-events#%ED%98%95%EC%8B%9D_%EC%A0%95%EC%9D%98)

2022-09-07 08:10 UTC, woose28 commented on frontend/src/components/FeedItem/index.tsx
> +          {isShowBriefChallengeName && challengeName.length > 9
제안해 주신 대로 수정했습니다! [d2775e8](https://github.com/woowacourse-teams/2022-smody/pull/385/commits/d2775e83534be6ab5e6f08d79088c2d3b4490ebc)

2022-09-07 08:20 UTC, woose28 commented
# 추가 작업 현황
## 너비가 좁은 디바이스에서 작성 버튼이 두 줄로 보이는 현상 해결
댓글 입력 창의 작성 버튼에 min-width 속성을 주어 문제를 해결했습니다!

## 너비가 좁은 디바이스에서 피드 아이템이 잘리는 현상을 해결
### 수정 전
<img width="596" alt="image" src="https://user-images.githubusercontent.com/52148907/188827883-d79e7ff5-149e-426b-a7d0-183a78957906.png">


### 수정 후
<img width="596" alt="image" src="https://user-images.githubusercontent.com/52148907/188827593-8c45e466-efe0-440a-9c07-faa2a623022b.png">

2022-09-08 02:59 UTC, ronci requested changes

2022-09-08 02:59 UTC, ronci commented on frontend/src/components/CommentInput/index.tsx
> +    padding: 0;
`padding: 0;`은 불필요한 코드 아닐까요??

2022-09-13 10:04 UTC, ronci approved these changes
고치느라 수고하셨어요 빅터! 미리 Approve할께요!

2022-09-13 10:08 UTC, merged