feat: (fe) 챌린지 이름 입력 시 자동 검색되는 기능 구현
woowacourse-teams/2022-smody pull request #395
Opened 2022-09-14 12:52 UTC by woose28

cloes #324 #394 

# 챌린지 이름 입력 시 자동 검색되는 기능 구현
- 검색 페이지에서 검샘어를 입력하면 `모든 챌린지 조회` API가 호출되도록 구현했습니다. ([37d9dae](37d9daed877acde9b2bb5c292cd027dada332c81))
  - debounce를 적용하여 API 요청 횟수를 최적화했습니다.
- 이에따라 SearchBar 컴포넌트에 사용되던 form 태그를 div 태그로 변경했습니다. ()
  - 검색 아이콘을 눌렀을 때는 여전히 API 요청이 가도록 구현했습니다.

# 검색 input 컴포넌트를 비제어 컴포넌트로 변경
- 검색어 입력 시 검색 페이지의  렌더링를 최적화 시키기 위해 input 컴포넌트를 비제어 컴포넌트로 변경했습니다.

최적화 테스트 조건은 다음과 같습니다.
1. 성능 측전 전 챌린지1과 챌린지2가 미리 생성돼 있어야한다.
2. 검색 페이지에서 챌린지1을 검색한다.
3. 검색 페이지에서 챌린지를 검색한다.
4. 검색 페이지에서 빈 키워드로 검색한다.

## 최적화 결과
### Before
- SearchPage가 총 30번 렌더링됐습니다.
<img width="1792" alt="최적화 전 SearchPage 렌더링 현황" src="https://user-images.githubusercontent.com/52148907/190157210-5acc0101-1da5-429d-b96b-5976f0f969ac.png">

### After
- SearchPage가 총 17번 렌더링됐습니다.
<img width="1792" alt="최적화 후 SearchPage 렌더링 현황" src="https://user-images.githubusercontent.com/52148907/190157251-e7ec415a-a1fb-4329-8870-b47e200a0903.png">

# ChallengeItem 렌더링 횟수 감소
- ChallengeItem 컴포넌트의 렌더링 횟수를 최적화하기 위해 React.memo 적용

최적화 테스트 조건은 다음과 같습니다.
1. 성능 측전 전 챌린지를 25개 생성한다.
2. 검색 페이지의 무한 스크롤을 맨 아래까지 내린다.

## 최적화 결과
### Before
- 마지막 커밋 단계에서 이전 페이지의 ChallengeItem이 렌더링됐습니다.
<img width="1789" alt="마지막 커밋 단계에서도 이전 페이지의 ChallengeItem이 렌더링 됨" src="https://user-images.githubusercontent.com/52148907/190158594-9fed1a23-7683-4787-9d08-1869d00523ac.png">

### After
- 마지막 커밋 단계에서 이전 페이지의 ChallengeItem이 렌더링 되지 않았습니다.
<img width="1789" alt="마지막 커밋 단계에서 이전 페이지의 ChallengeItem이 렌더링 안됨" src="https://user-images.githubusercontent.com/52148907/190158714-a4b10b35-4f9f-4bc8-9c24-93e96498a5e9.png">

2022-09-15 09:20 UTC, ronci requested changes
수고하셨어요 빅터!
몇개 comment 달았는 데 한 번 확인해주시면 좋을 것 같아요!

그리고 전체적으로 type을 인라인으로 바로 사용했는 데,
저희가 저번에 말했던 컨벤션에서는 type을 분리해서 type.ts파일에 정의 후
import해서 사용하는 거로 얘기를 했던 것 같아요!
그래서 혹시 이렇게 구현한 이유가 무엇이고 컨벤션을 어떻게 맞추면 좋을 지 다시 얘기해봐도 좋을 것 같아요!

2022-09-15 09:20 UTC, ronci commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +};
indexedDB 관련된 로직들을 따로 indexedDB를 관리하는 파일에 분리하는 것은 어떨까요?

2022-09-15 09:20 UTC, ronci commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +  const searchInput = useRef<null | HTMLInputElement>(null);
여기도 위처럼 null type을 따로 표기하지 않아도 괜찮을 것 같아요!

2022-09-15 09:20 UTC, ronci commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +    }
각 if문에 `renderSnackBar({ status: 'ERROR', message: checkingResult.message });` 코드를 넣고 return을 해주는 건 어떨까요?

2022-09-16 05:47 UTC, woose28 commented on frontend/src/components/SearchBar/index.tsx
>      display: flex;
아이구 제가 FlexBox만 적용하고 중복되는 스타일을 제거하는 걸 깜빡했네요..!
해당 부분 수정했습니다~

[6df74df](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/6df74dff6fe7f492e8b2c678319b5d4dd5fe05fe)

2022-09-17 07:45 UTC, woose28 commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +const MAX_VALUE_LENGTH = 30;
제안해 주신 대로 상수 분리를 진행했습니다~

- `EMPTY_REGEX_RULE`의 경우 regex.ts로 이동시켰습니다.
- `MAX_VALUE_LENGTH`는 `MAX_CHALLENGE_NAME_LENGTH`으로 이름을 변경한 후 domain.ts로 이동시켰습니다.

[e8af950](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/e8af950b01bbdeeb4c680dfff3479a68846bb14c)

2022-09-17 07:52 UTC, woose28 commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +  const searchInput = useRef<null | HTMLInputElement>(null);
해당 부분 제안해 주신 대로 수정했습니다~

[b198fcf](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/b198fcffce074d9e641e326f58880087e6d0471c)

2022-09-17 07:54 UTC, woose28 commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +    }
renderSnackBar의 중복된 사용을 방지하고 싶어서 위처럼 코드를 작성했는데, 다시 확인하니 오히려 가독성을 해치는 코드가 된 거 같네요. 이 부분 수정했습니다~

[4f02909](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/4f029094ea4f74f5366907e67abbf40aab076bd2)

2022-09-18 03:09 UTC, woose28 commented on frontend/src/hooks/useDebounce.ts
> +  const timerId = useRef<null | NodeJS.Timeout>(null);
맞아요. `NodeJs.Timeout` 타입은 적절하지 않네요! 실제로 코드에서 setTimeout을 작성하면 [Node js의 setTImtout](https://nodejs.org/ko/docs/guides/timers-in-node/#settimeout)으로 인식하고 있네요. 그래서 반환 값도 NodeJs의 Timeout 객체였고요!

결국 실행 시에는 브라우저의 setTimtout으로 인식하겠지만, 현재 우리 코드에서 NodeJs 타입이 들어가는 게 적절해 보니진 않네요!
따라서 `window.setTImtout()`으로 대체하여 브라우저의 setTimtout 함수와 타입이 일치되도록 수정했습니다!

[f182bf1](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/f182bf1aa668477f31ad50e2819dfd5efa1b9c96)

추가로, useSnackBar에서 사용되는 setTimtout 함수도 호출 방식을 수정했습니다~

[69ae852](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/69ae8526a64ea4734eac8e84706ccf927924b227)

2022-09-18 03:26 UTC, woose28 commented on frontend/src/hooks/useDebounce.ts
> +  const timerId = useRef<null | NodeJS.Timeout>(null);
첨부 글 감사합니다👍
현재 useRef는 `변경이 가능한 로컬 변수`를 이용하려고 사용했습니다. 그렇기 때문에 useRef의 반환 값은 `RefObject`가 아니고, 변경가능한 `MutableRefObject`이 돼야해요!
null의 경우 timerId가 비어있다는 것을 의도적으로 표현하기 위해 사용했습니다.
따라서 tiemrId에 null과 setTimtout의 반환 값을 저장하기 위해서, number 타입과 null 타입을 동시에 genertic 타입으로 지정했습니다!

2022-09-18 03:33 UTC, woose28 commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +};
`indexedDB.js` 파일에 indexedDB 관련 코드가 모여있습니다! 하지만 그럼에도 파일 분리가 필요해 보이는 이유는 여전히 추상화가 덜 됐기 때문이겠죠. 현재 indexDB에 데이터를 저장하는 여러 파일에서 위와 같은 패턴이 동일하게 사용되고 있는데, 전체적으로 리팩터링을 하는 것도 좋은 방향일 거 같아요! 그리고 해당 브랜치에서 작업이 너무 커지는 것을 방지하기 위해 리팩터링을 다른 브랜치에서 진행하면 좋을 거 같은데 괜찮을까요?

2022-09-18 03:38 UTC, woose28 commented
> 그리고 전체적으로 type을 인라인으로 바로 사용했는 데,
저희가 저번에 말했던 컨벤션에서는 type을 분리해서 type.ts파일에 정의 후
import해서 사용하는 거로 얘기를 했던 것 같아요!
그래서 혹시 이렇게 구현한 이유가 무엇이고 컨벤션을 어떻게 맞추면 좋을 지 다시 얘기해봐도 좋을 것 같아요!

현재, page나 component의 경우 말씀해 주신 대로 type.ts로 타입이 분리돼 있지만, hooks 디렉터리 아래 있는 hook들의 경우 모두 한 파일에 type이 정의돼 있어요. 이 부분에 대해서 다음 회의 때 합의를 하고 다른 코드들도 수정하면 좋을 거 같아요!

2022-09-19 04:06 UTC, ronci commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +};
넵 따로 브랜치를 사용해서 리팩터링하는 것도 좋을 것 같네요!

2022-09-19 04:10 UTC, ronci commented on frontend/src/pages/SearchPage/useSearchPage.ts
> +};
https://github.com/woowacourse-teams/2022-smody/issues/401 이슈 추가했습니다!

2022-09-19 04:17 UTC, ronci approved these changes
그러면 typescript 리팩터링하면서 한 번 이야기 해보는 것이 좋을 것 같네요!
1. type 분리는 어떤 방식으로 할 지
2. (value : string)처럼 간단한 타입에 대해서는 어떻게 표현할 지
현재 생각나는 것은 이 정도인데 나중에 천천히 얘기해봅시다!

코드 수정하시느라 수고하셨어요 빅터!

2022-09-19 04:18 UTC, merged