feature : (be) 랭킹 활동 및 기간 조회 기능 구현
woowacourse-teams/2022-smody pull request #478
Opened 2022-09-30 11:21 UTC by tonic523

## 구현한 기능
- 랭킹 기간 목록을 최신순으로 정렬하여 조회한다.
- 랭킹 기간에 해당하는 랭킹 활동 목록을 순위별로 정렬하여 조회한다.
- 사이클 인증 시 인증한 시간에 알맞는 랭킨 기간에 있는 활동에 점수를 갱신한다.

## 데이터베이스 다이어그램
- 랭킹 기간: RankingPeriod
- 랭킹 활동: RankingActivity
![image](https://user-images.githubusercontent.com/59171113/193257545-a4d6b1a0-6a3a-4834-83cf-7efeec11356b.png)

2022-09-30 11:22 UTC, ldk980130 commented
## 사이클 인증을 했을 때 랭킹 점수가 올라가는 로직은 하나의 트랜잭션인가? 아니다

회원이 챌린지를 인증하면 주간 랭킹 점수에 반영 된다.

챌린지 인증 → `CycleService.increaseProgress()`

랭킹 관련 로직 → `RankingService`

랭킹 로직과 챌린지 로직이 강한 결합을 갖는 것을 막고 랭킹에 장애가 발생해도 챌린지 인증은 정상 동작 시키기 위하여  이벤트(`@TransactionalEventListener`) + 비동기 처리`(@Async`)를 하기로 선택했다.

```java
@TransactionalEventListener
@Async("asyncExecutor")
public void handle(CycleProgressEvent event) {
    Cycle cycle = event.getCycle();
		CycleDetail cycleDetail = cycle.getLatestCycleDetail();
    LocalDateTime progressTime = cycleDetail.getProgressTime();
    rankingService.findInProgressActivity(progressTime, cycle.getMember())
            .forEach(activity -> activity.active(cycleDetail.getProgress()));
    }
}
```

`CycleService.increaseProgress()`는 `CycleProgressEvent`를 발행하고 위 메서드는 이 이벤트를 구독했다. `CycleProgressEvent`가 발행되면 위 로직이 실행되면서 랭킹 점수에 관한 로직을 실행할 것이다.

## 인증 기간이 항상 존재해야 하는 로직의 구현 방법

랭킹 점수를 올리기 위해서는 `RankingActivity`(랭킹 활동)을 생성해야 하는데 `RankingActivity`는 인증 기간(`RankingPeriod`)가 존재 해야 한다.

![image](https://user-images.githubusercontent.com/78652144/193259143-6019ee38-4b4b-4fb5-88f0-8dc29fa93149.png)

즉 챌린지 인증에 따라 랭킹 점수를 집계하기 위해서는 항상 `RankingPeriod`는 존재해야 하며 현 정책상 `RankingPeriod`는 7일 간격으로 매주 월~일의 기간이다.

`RankingPeriod`를 생성하는 api는 존재하지 않기 때문에 항상 존재해야한다는  정합성을 보장하기 위해 두  가지 방법을 생각했다.

- `@Scheduled`를 사용해 매주 일요일 밤 11시 55분에 다음 주 `RankingPeriod`를 생성한다.
- 첫 사용자의 챌린지 인증이 발생했을 때 함께 생성하고, 그 뒤부터 인증하는 사용자들은 있는 `RankingPeriod`를 조회해서 사용한다. (사용자가 인증하지 않았으면 보여줄 랭킹이 없다고 판단)

스케줄러를 사용하는 방법은 일요일 밤 등의 특정 시간에 장애가 발생하면 정합성이 안 맞는 문제가 발생하고 일요일 후에 배포를 하면 `RakingPeriod를` 직접 넣어줘야 하는 등 관리하기가 까다롭다고 판단했다. 그래서 첫 인증 발생 요청을 판단하여 `RankingPeriod`를 생성하기로 결정했다.

## 동시에 첫 인증이 발생했을 때 동시성 문제

`RankingPeriod`는 `‘시작 날짜’`와 `‘기간’`의 두 속성으로 판별 된다. 같은 날에 시작해 같은 기간 동안 지속되는 2개의 `RankingPeriod`는 필요 없고 있어서는 안 된다. 

때문에 동시에 두 사용자가 그 주의 첫 인증을 할 경우 같은 기간 동안 지속되는 `RankingPeriod`가 생기게 되는 동시성 문제가 발생한다.

### 해결 첫 번째 단계 - Unique 제약

`시작 날짜`와 `기간`의 복합 컬럼으로 유니크 제약을 설정했다.

![image](https://user-images.githubusercontent.com/78652144/193259187-8a6d5b17-da64-4973-9657-addea1a7c3ed.png)

이렇게 되면 한 트랜잭션에서 이 조합으로 이미 insert 쿼리를 날리면 (설령 커밋 전이라고 해도) 다른 트랜잭션에서는 이 조합으로 insert를 날리지 못하고 대기하게 된다.

먼저 insert를 한 트랜잭션이 커밋되면 두 번째 트랜잭션은 유니크 제약으로 인해 예외를 발생시키고, 롤백 되면 정상 커밋 된다.

Unique 제약으로 lock을 걸지 않고도 한 주에 한 `RankingPeriod`를 생성할 수 있게 되었다.

### 챌린지 인증과 랭킹 점수 간의 정합성 문제 발생

첫 번째 트랜잭션에서 먼저 `RankingPeriod`를 insert했기 때문에 두 번째 트랜잭션이 예외를 발생하는 상황은 `RankingPeriod`를 하나만 생성하지만 두 번째 트랜잭션은 예외를 맞고 롤백하게 된다.

그럼 두 번째 트랜잭션은 챌린지 인증은 했지만 점수는 사라지게 된다. 정책적으로 이는 말이 안 된다.

### 해결 두 번째 단계 - try/catch를 사용한 트랜잭션 병렬 처리

![image](https://user-images.githubusercontent.com/78652144/193259224-38181ddc-40c3-4c56-9927-1bfaa8798beb.png)

1. `try` 문 안에서 `RankingPeriod`가 없으면 생성하는 로직과 점수를 올리는 로직을 실행하게 된다.
2. 만약 동시성 문제 때문에 예외가 발생하여 `catch` 문으로 오게 되면 첫 번째 트랜잭션이 이미 `RankingPeriod`를 생성해 주었을 것이다.
3. 여기서 아무 로직도 실행하지 않으면 점수가 사라지겠지만 한 번 더 점수를 올리는 로직을 실행하여 다른 트랜잭션이 먼저 만들어준 `RankingPeriod`를 조회해 점수를 올린다.

여기서 같은 트랜잭션 안에서는 repeatable-read 격리 속성 때문에 같은 결과가 조회되지 않냐고 의문을 가질 수도 있다.

이를 해결하기 위해 `@Transactional` 어노테이션을 쓰지 않고 `TransactionTemplate`을 이용해 try에서의 트랜잭션을 커밋 시키고 다시 병렬적으로 다음 트랜잭션을 실행하고 있다.

`catch` 문에서는 이미 커밋된 `RankingPeriod`를 읽을 수 있게 되면서 정상적으로 다시 점수를 올릴 수 있게 된다.

2022-10-01 09:53 UTC, tonic523 commented
## 이슈
`http://localhost:8080/ranking-periods?sort=startDate:desc` 로 요청할 때 500 에러가 발생한다.\
이유는 쿼리파라미터를 받는 `PagingParams` 에서 sort만 받는 생성자가 없다.\
```java
public PagingParams(String sort) {
    this.sort = sort;
}
```

2022-10-04 03:54 UTC, jojogreen91 requested changes
전반적으로 너무 깔끔하고 좋네요. 굳굳굳
메서드 이름변경같은 부분의 코멘트만 좀 있습니다.
화이팅!

2022-10-04 03:54 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/repository/RankingPeriodRepository.java
> +    List<RankingPeriod> findAllByStartDateBefore(LocalDateTime time);
매개변수 이름도 startDate 라고 하면 어떤가요?

2022-10-04 03:54 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
> +    public List<RankingActivity> findInProgressActivity(LocalDateTime time, Member member) {
메서드 이름을 현재 period 에 해당하는 액티비티를 가져온다는 느낌으로 바꾸면 어떨까요
inProgress 이 사이클과 관련한 느낌이 들어서 피하는게 이해가 더 좋을거 같아서요

2022-10-04 03:54 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
> +    public List<RankingPeriod> findInProgressPeriod(LocalDateTime time) {
왜 퍼블릭인가요?

2022-10-04 03:54 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
> +    public List<RankingActivityResponse> findAllActivity(Long rankingPeriodId) {
랭킹 줄세우기가 적용된 액티비티라는 느낌을 줄수 있는 메서드 이름이면 어떨까요?

2022-10-04 08:30 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/Cycle.java
> +        return getLatestCycleDetail().getProgressTime();
원래 로직이 잘못되어 있었습니다. `get(0)`을 하게 되면 최신이 아니라 시간 상 가장 오래된 인증이 나오도록 로직이 짜여 있어서 고쳤습니다!

2022-10-04 08:30 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/member/service/MemberService.java
> +    public List<SearchedMemberResponse> findAll(PagingParams pagingParams) {
`Member `패키지에서 `mention`에 대한 워딩을 모두 빼도록 알파에게 코드리뷰 했었었는데 미쳐 빼지 못한 부분이 있길래 하는김에 수정했습니다.

2022-10-04 08:38 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingActivity.java
> +    public static RankingActivity zero(Member member, RankingPeriod period) {
혹시 `create`나 `of `같은 정적 팩터리 메서드 네이밍 컨벤션을 말하시는 걸까요? 사실 맥락상 `0점으로 생성한다`라는 느낌을 주고 싶어서 위의 네이밍을 선택한 것이었습니다.  그럼에도 `of`처럼 컨벤션을 지키는 것이 좋을까요? 아니면 `ofZeroPoint()`는 어떨까요.

토닉과 저는 `RankingActivity.zeroPoint()`에 마음이 더 가네요ㅎㅎ

2022-10-04 08:44 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/repository/RankingPeriodRepository.java
> +    List<RankingPeriod> findAllByStartDateBefore(LocalDateTime time);
변경하겠습니다!

2022-10-04 08:45 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingActivity.java
> +        this.point += Point.valueOf(progress.name())
단순히 상수 이름이 같아서 위와 같은 로직으로 짰는데 이름은 바뀔 수도 있고 참조를 가지고 있는 게 더 정확하겠네요!

2022-10-04 08:54 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
> +    public List<RankingActivity> findInProgressActivity(LocalDateTime time, Member member) {
`현재 기간에 맞는 활동을 가져 온다`라는 의미를 영어 메서드로 나열하기엔 긴 느낌이 있어서 `진행 중인 활동`의 의미를 내포하기 위해 `InProgress`라는 표현을 썼습니다. 

`List<Cycle> CycleService.findInProgres..()`
`List<RankingActivity> RankingService.findInProgres..()`

별 문제 없다면 이 네이밍율 유지하고 싶은데 많이 헷갈릴까요?

아니면 겹치지 않는 다른 이름이 있을까요?

2022-10-04 10:39 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
> +    public List<RankingPeriod> findInProgressPeriod(LocalDateTime time) {
수정하겠습니다~

2022-10-05 01:23 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingActivity.java
> +    public static RankingActivity zero(Member member, RankingPeriod period) {
저는 `ofZeroPoint` 라는 이름이 `RankingActivity. ofZeroPoint` 처럼 붙여 읽었을 때 읽는 흐름이 좋아서 선호하는데 어떻게 생각하시나용

2022-10-05 01:26 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingService.java
> +    public List<RankingActivity> findInProgressActivity(LocalDateTime time, Member member) {
음 저도 딱 떨어지는건 없는거 같긴한데 findCurrentActivity 같은건 어떤가요
별로면 그냥 inProgress 해도 괜찮을거 같아요

2022-10-05 05:22 UTC, jojogreen91 approved these changes
수고하셨습니다!

2022-10-05 05:22 UTC, merged