feat : (be)멘션 기능 추가
woowacourse-teams/2022-smody pull request #492
Opened 2022-10-04 11:44 UTC by bcc0830

Close #471 

## 구현한 기능
- 특정 글자로 멤버들을 조회시, 대응되는 멤버들의 목록을 응답하는 기능
- 댓글로 멘션된 회원들에게 보낼 알람을 DB에 저장하고 실제로 발신까지 하는 기능

2022-10-04 12:52 UTC, ldk980130 requested changes
맨션 알림 기능 구현 코드 잘 봤습니다! 이벤트를 발행하는 쪽과 이벤트를 처리하는 쪽의 역할과 책임에 대해 다시 한 번 얘기 나눠보면 좋을 것 같아요!

2022-10-04 12:52 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +        Member mentioningMember = memberService.findMember(new TokenPayload(event.getMentioningIds()));
member를 찾는 메서드는 2가지가 있는데요.

`search `- 있으면 반환하고 없으면 예외
`findMember `- 있으면 반환하고 없으면 id가 없는 비회원을 반환

챌린지 관련 로직에서 비회원인 경우도 처리해야해서 `findMember`를 추가한 적이 있어요. 그런데 이 로직 상에선 맨션을 보내는 사람이 없으면 안되니까 `search`를 쓰는 게 더 좋을 것 같습니다.

2022-10-04 12:52 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +    public void handle(MentionCreateEvent event) {
메서드가 길어요~ 적절한 이름으로 분리하면 더 가독성이 좋아질 것 같아요

2022-10-04 12:52 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    public void publishMentionEvent(TokenPayload tokenPayload,
`PushNotificationService`에겐 `push_notification` 테이블에 대한 관리 책임이 있다고 생각하는데 `push_notification` 리소스를 db에 저장하는 역할까지 이벤트로 넘겨버린 이유가 있을까요?

그리고 이 메서드는 단순히 알림을 저장하는 역할을 할 뿐이지 멘션만을 위한 알림이라고는 생각이 안드는 것 같아요. 여러 회원의 알림을 저장한다는 의미만 있어도 충분할 것 같아요

2022-10-04 12:52 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/push/controller/PushNotificationControllerTest.java
> +	@DisplayName("멘션 알람을 저장하면 200 응답을 반환한다.")
테스트 이름도 마찬가지라고 저는 생각이 들어요. 단순히 여러 사람의 알림을 저장하는 api라고 생각이 들어요. 프론트에서 `PushCase`와 `pathId`를 다르게 주면 멘션이 아닌 다른 알림이 되어버리니까요.

2022-10-05 01:37 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/member/controller/MemberController.java
> +    public ResponseEntity<List<MentionResponse>> findAll(@LoginMember TokenPayload tokenPayload,
지우셈

2022-10-05 01:38 UTC, tonic523 requested changes

2022-10-05 01:38 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +    public void handle(MentionCreateEvent event) {
동의합니다~

2022-10-05 01:38 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    public void publishMentionEvent(TokenPayload tokenPayload,
이 부분은 더즈가 말한 피드백을 반영하다보면 많이 수정될 것 같아요. 현재 구조에서 이 메서드에 대한 테스트코드가 없는데 수정된 이후에도 service에 대한 테스트도 구현하면 좋을 것 같습니다

2022-10-05 01:41 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/member/controller/MemberController.java
> +    public ResponseEntity<List<MentionResponse>> findAll(@LoginMember TokenPayload tokenPayload,
토큰은 안쓰니까 지우면될것 같구
api 이름도 근데 멘션을 위한 모든 회원 조회라는게 담겨 있으면 좋을거 같습니다.
특히 dto 가 멘션리스폰스라서 뭔가 헷갈리는거 같아요

2022-10-05 01:44 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/domain/MentionCreateEvent.java
> +    private final Long mentioningIds;
멘션드 아이디랑 멘셔닝 아이디의 차이가 뭔가요?

2022-10-05 01:45 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/dto/MentionNotificationRequest.java
> +    private Long pathId;
패스 아이디는 뭐하는 값인가요?

2022-10-05 01:47 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +    public void handle(MentionCreateEvent event) {
동의합니다

2022-10-05 01:48 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/controller/PushNotificationController.java
> +    public ResponseEntity<Void> saveMentionNotification(@LoginMember TokenPayload tokenPayload,
이건 뭐하는 api 인가요?

2022-10-05 01:50 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +                .collect(Collectors.toUnmodifiableList());
꼼꼼하게 하기 위한 불변 리스트?

2022-10-05 01:54 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +        List<PushSubscription> subscriptions = pushSubscriptionService.searchByMembers(mentionedMembers);
이런거 하나하나 메서드 분리했으면 훨씬 가독성이 좋았을텐데 말이죠 알파

2022-10-05 01:54 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +        }
이런거 하나하나 메서드 분리했으면 훨씬 가독성이 좋았을텐데 말이죠 알파

2022-10-05 02:11 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/push/domain/MentionCreateEvent.java
> +    private final Long mentioningIds;
뭔가 더 좋은 이름이 없을까 고민되는데 저도 떠오르는게 없네요

2022-10-05 02:12 UTC, jojogreen91 requested changes
알파 코드 잘봤습니다 수고하셨어요
근데 이슈 링크를 달아놨는데 안에 아무것도 없네요.
어떤걸 어떤방식으로 개발했고 api 설계는 어떻게 했고 같은 이슈 내용이 있어야할것 같습니당

2022-10-05 05:15 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/controller/PushNotificationController.java
> +    public ResponseEntity<Void> saveMentionNotification(@LoginMember TokenPayload tokenPayload,
수정하였습니다

2022-10-05 05:23 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +        Member mentioningMember = memberService.findMember(new TokenPayload(event.getMentioningIds()));
수정하였습니다

2022-10-05 05:23 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +    public void handle(MentionCreateEvent event) {
메소드 분리 진행하였습니다

2022-10-05 06:10 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    public void publishMentionEvent(TokenPayload tokenPayload,
MentionPushEventListener를 삭제히고 notification을 service에서 담당하도록 수정하였습니다. 더불어 원래 진행되던 테스트 코드도 삭제하고 service 테스트 코드에 추가하였습니다

2022-10-05 06:10 UTC, bcc0830 commented on backend/smody/src/test/java/com/woowacourse/smody/push/controller/PushNotificationControllerTest.java
> +	@DisplayName("멘션 알람을 저장하면 200 응답을 반환한다.")
수정하였습니다

2022-10-05 06:12 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/member/controller/MemberController.java
> +    public ResponseEntity<List<MentionResponse>> findAll(@LoginMember TokenPayload tokenPayload,
메소드 이름은 현행으로 유지하되, dto Response 네이밍만 "특정 조건에 따른 멤버들의 목록"이라는 의미로 MembersResponse로 바꾸는 건 어떤가요?

2022-10-05 06:13 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/domain/MentionCreateEvent.java
> +    private final Long mentioningIds;
표준 수동/능동 표현을 사용해서 Mentioning이 능동형으로서, 멘션을 날리는 사람이라고 생각하면 감사하겠습니다

2022-10-05 06:14 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/dto/MentionNotificationRequest.java
> +    private Long pathId;
네이밍의 필요성은 공감합니다. 다만, 차후 알람 서비스 전체 리팩토링 시 해당 부분을 반영하는 것은 어떠신가요?

2022-10-05 06:14 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/event/MentionPushEventListener.java
> +        }
메소드 분리 진행하였습니다

2022-10-05 06:48 UTC, tonic523 approved these changes

2022-10-05 06:57 UTC, ldk980130 requested changes
사소한 거지만 체크해주세요!

2022-10-05 06:57 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +        publisher.publishEvent(new MentionCreateEvent(mentionedIds, mentioningId, cycleDetailId));
이벤트를 사용안하니까 필요없지 않을까요? `MentionCreateEvent`도 필요 없을 것 같아용

2022-10-05 06:57 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +                                 MentionNotificationRequest mentionNotificationRequest) {
이 메서드는 어떨 때 사용되는 메서드일까요. 여러 알림을 저장할 때? 아니면 멘션 알림에 대해서만? DTO 이름에 대해서 생각해볼 필요가 있겠네용

그리고 여러개를 저장하는 메서드니까 `sendNotifications`라고 하는 편이 더 좋아보여요.

2022-10-05 06:57 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    }
이것만 보면 멘션 알림을 생성하는 것 같아서 이 api를 멘션 알림에 대해서만 처리하도록 바꿔야하나 싶네요.

만약 이 api로 다른 `PushCase` 알림을 요청한다면 어떻게 처리해야 하는지 고민해보는 것도 좋겠네요ㅎㅎ 지금 당장은 맨션밖에 없으니까 괜찮을 수도 있을 것 같습니다.

반영 안하셔도 됩니다!

2022-10-05 07:34 UTC, bcc0830 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +        publisher.publishEvent(new MentionCreateEvent(mentionedIds, mentioningId, cycleDetailId));
삭제하였습니다

2022-10-05 07:35 UTC, ldk980130 approved these changes
피드백 반영 수고하셨습니다!!

2022-10-06 01:23 UTC, merged