feat: (be) error 발생 시 issue 자동 생성 기능 추가
woowacourse-teams/2022-smody pull request #544
Opened 2022-10-12 06:15 UTC by ldk980130

close #536 

![image](https://user-images.githubusercontent.com/78652144/195264243-cafaebdc-1f0e-48ed-ae70-af3a2078ebe3.png)

- `BusinessException`이 아닌 모든 예외가 이슈로 자동 생성
- `prod` 환경에서만 이슈가 자동 생성 됨
- `Assignees`는 백엔드 4인이 자동 등록
- `Labels`는 '장애', '에러 해결', '백엔드'로 자동 등록

2022-10-12 06:53 UTC, tonic523 approved these changes
👍

2022-10-14 01:57 UTC, jojogreen91 requested changes
리뷰 확인 부탁드립니다 ㅎㅎㅎ :)

2022-10-14 01:57 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
> +    public RestTemplate restTemplate() {
레스트 템플릿을 빈으로 등록해서 사용해도 문제가 없나요?
상태를 가진다거나 그런게 없나보군요??

2022-10-14 01:57 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/exception/GithubApi.java
> +	private static final String REPO_URL = "https://api.github.com/repos/woowacourse-teams/2022-smody/issues";
상수화가 깔끔해서 이해기 편하네요 굳굳

2022-10-14 01:57 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/exception/IssueCreateRequest.java
> +public class IssueCreateRequest {
이거 GitHub API 를 위한 dto 인거 같은데 익셉션 패키지 안에 dto 패키지 하나 만드는건 어떤가요?

2022-10-14 01:57 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/exception/ControllerAdvice.java
> +    private static final String ISSUE_CREATE_ENV = "prod";
ISSUE_CREATE_PROFILE 은 어떤가요?

2022-10-14 01:57 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
> +        return new RestTemplate();
RestTemplate 를 쓰는 다른 곳에서도 빈으로 사용하도록 변경하면 어떨까요?
이미지, OAuth 등에서 사용하고 있는거 같은데

2022-10-14 02:01 UTC, jojogreen91 commented on backend/smody/src/test/java/com/woowacourse/smody/exception/UnexpectedErrorGithubIssueTest.java
> +	private MockEnvironment environment;
머싯네요

2022-10-14 02:02 UTC, jojogreen91 commented on backend/smody/src/test/java/com/woowacourse/smody/exception/UnexpectedErrorGithubIssueIntegrationTest.java
> +class UnexpectedErrorGithubIssueIntegrationTest extends ControllerTest {
UnexpectedErrorGithubIssueTest 와 이 테스트 클래스를 분리한 이유가 뭔가요?

2022-10-14 02:12 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
> +    public RestTemplate restTemplate() {
네 단순히 유틸적인 메서드만 수행하고 있고 소셜 로그인할 때와 깃헙 api를 쓸 때 반복하여 생성하길래 빈으로 등록하면 싱글턴으로 사용할 수 있다고 판단했습니다.

2022-10-14 02:12 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/exception/IssueCreateRequest.java
> +public class IssueCreateRequest {
Exception 패키지 안에 클래스가 많아지긴 했더라구요. 반영하겠습니다.!

2022-10-14 02:13 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/exception/UnexpectedErrorGithubIssueIntegrationTest.java
> +class UnexpectedErrorGithubIssueIntegrationTest extends ControllerTest {
애플리케이션 컨텍스트를 띄우지 않는 단위 테스트와 실제로 예외가 터졌을 때 `@ExceptionHandler`가 잡아서 처리하는 통합 테스트의 관점으로 나눴습니다.

2022-10-14 02:14 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
> +        return new RestTemplate();
이미 변경했스빈다!!

![image](https://user-images.githubusercontent.com/78652144/195746462-13862ba5-5863-4c9e-b2ab-92461f9c9f2e.png)

2022-10-14 02:23 UTC, jojogreen91 approved these changes
고생하셨습니다 :)

2022-10-14 03:05 UTC, merged