feature: (be) 나의 보낸 알림 모두 삭제 기능 구현
woowacourse-teams/2022-smody pull request #558
Opened 2022-10-14 07:07 UTC by ldk980130

## 나의 보낸 알림 삭제(DELETE)

보낸 알림 모두 삭제

### Request

```json
DELETE /push-notifications/me
Authorization: Bearer ${accessToken}
```

### Response

```json
204 NoContent
```
![image](https://user-images.githubusercontent.com/78652144/195784038-c9911bef-078f-4933-9091-0338ddddb753.png)

![image](https://user-images.githubusercontent.com/78652144/195784082-f6799b90-2e49-4142-a750-6d09b300f87a.png)

![image](https://user-images.githubusercontent.com/78652144/195784145-44c78378-1a7b-4015-841e-cd9dcd99f028.png)

2022-10-14 07:44 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    public void deleteCompleted(Member member) {
알림 발송이 완료된 알림들을 모두 삭제하는 로직이네요
메서드 명이 조금 더 구체적이면 어떨까요?
예를 들어

- `deleteByMemberAndPushStatus(Member member, PushStatus pushStatus)`

2022-10-14 07:51 UTC, tonic523 requested changes
더즈 테스트도 꼼꼼히 잘 작성해주었네요!
메서드 네이밍 관련된 피드백만 확인해주시면 될 것 같습니다.

2022-10-14 07:51 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    }
알림 발송이 완료된 알림들을 모두 삭제하는 로직이네요 메서드 명이 조금 더 구체적이면 어떨까요? 예를 들어

deleteByMemberAndPushStatus(Member member, PushStatus pushStatus)

2022-10-14 07:51 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationApiService.java
> +    }
apiService와 일반 Service를 잘 분리해주었네요! 👍

2022-10-14 11:28 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    }
`PushNotificationRepository`에 토닉이 적어준 이름이 있는데 서비스 클래스의 메서드도 변경되면 좋을 것 같다는 말인가요?

2022-10-15 07:22 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    }
네 맞아요!

2022-10-15 09:25 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    }
service 클래스의 메서드 시그니처가`deleteByMemberAndPushStatus(Member member, PushStatus pushStatus)`가 된다면 repostiory 메서드를 바이패스만 하는 역할을 가지게 될 것같아요.

물론 상황에 따라 바이패스해도 상관 없지만 서비스 레이어에서는 '완료된'이라는 의미를 넣어 네이밍해 주는 것이 좋다고 생각이 들었고 (Cycle 서비스의 `findInProgress` 처럼요!) Member를 파라미터로 넣어주고 있으니 member에 대한 설명은 굳이 필요 없다고 들었어요.

그래도 조금 더 구체적으로 이름을 변경하면 좋을 것 같다는 의견 자체에는 어느정도 동의를 하는데 `deleteCompletedByMember()`는 어떨까요?

2022-10-16 06:37 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
> +    }
오 좋네요! 더즈가 말해준 메서드명으로 수정해주세요 ㅎㅎ

2022-10-16 06:37 UTC, tonic523 approved these changes

2022-10-17 04:43 UTC, merged