feat : (be) 챌린지 필터링 기능 구현
woowacourse-teams/2022-smody pull request #559
Opened 2022-10-14 07:16 UTC by tonic523

## 챌린지 필터링 기능 구현

### `/challenges?sort=random&size=10`
- 임의의 챌린지를 조회

### `/challenges?sort=popular&size=10`
- 현재 진행중인 참가자 순으로 조회

2022-10-14 11:59 UTC, ldk980130 requested changes
토닉과 쬬그린의 코드 잘 봤습니다. 짧은 시간에 깔끔하게 구현해주신 것 같아요.

전체적으로 3부분에 대해서만 request change 드립니다.
1. `popular + random + 일반 조회` 로직을 담당하는 service 메서드의 크기가 너무 큰 것 같아요.
2. 테스트 케이스를 좀 더 늘렸으면 좋겠습니다.
3. n+1 해결해주세요

2022-10-14 11:59 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
>          return getChallengeTabResponses(challenges, member, challengingRecords);
한 메서드의 책임이 너무 무거워 보여요. 어떤 조건에 따라 로직이 이렇게나 다르다면 다른 메서드로 분리해야하지 않을까 싶어요.

`random`까지는 `SoltSelection`으로 공통 처리를 한 것 같으니 괜찮은데 `popular`는 `Controller`에서부터 분기가 들어가면 어떨까요?

2022-10-14 11:59 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
> +                .collect(toList());
`ChallegneRecords` 활용 👍 
추가적으로 사이클 개수로 역정렬하는 로직도 `ChallegneRecords`에게 맡기면 `service` 코드가 더 깔끔해질 것 같아요!
```
 private List<ChallengeTabResponse> getChallengeTabResponsesWhenPopular(LocalDateTime searchTime,
                                                                           PagingParams pagingParams,
                                                                           Member member) {
        List<Cycle> cycles = cycleService.findInProgress(searchTime);
        ChallengingRecords challengingRecords = ChallengingRecords.from(cycles);
        List<Challenge> challenges = chllengingRecords.sortByCycleCountDesc(challengingRecords);
        List<Challenge> pagedChallenges = CursorPaging.apply(challenges, null, pagingParams.getSize());
        return getChallengeTabResponses(pagedChallenges, member, challengingRecords);
    }
```

2022-10-14 11:59 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/db_support/SortSelection.java
> +                NumberExpression.random().asc()
random을 간단하게 구현할 수 있네요 👍

2022-10-14 11:59 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/repository/ChallengeRepositoryTest.java
> +        assertThat(actual).hasSize(2);
좋은 테스트 방법이 없을까 궁금하네요

2022-10-14 11:59 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +        fixture.사이클_생성_NOTHING(더즈_ID, 스모디_방문하기_ID, LocalDateTime.now());
1. given이 모두 진행 중인데 진행 중이지 않은 `cycle`이 있는 상태에서도 그 `cycle`들이 잘 걸러지는 지도 테스트 해보면 좋을 것 같아요
2. 챌린지가 총 3개인데 3개를 가져오는 로직이라 페이징이 잘 되는지도 이 테스트만 봐서는 알 수 없다고 생각합니다.
3. 진행 중인 참가자가 없는 챌린지가 조회 안되는 지도 테스트하면 좋을것 같아요.

2022-10-14 11:59 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +                .containsExactly("미라클 모닝", "오늘의 운동", "스모디 방문하기");
n+1 발생하는데 확인해주세요~!!
![image](https://user-images.githubusercontent.com/78652144/195841316-d4cbcc62-128c-46e7-80b9-0e8ae83f8b69.png)

2022-10-15 07:17 UTC, tonic523 reviewed
더즈 디테일하게 리뷰 주셔서 감사해요!
리뷰를 보니 제가 놓친 부분이 많았었네요 ㅠㅠ 어떤 기능을 구현하게 되면 쿼리문은 항상 확인해주어야 하는 것 같아요. 더즈가 주신 리뷰 대부분은 반영했으니 확인 부탁드립니다. 추가로 코멘트에 제 의견도 남겨놓았어요!

2022-10-15 07:17 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +        fixture.사이클_생성_NOTHING(더즈_ID, 스모디_방문하기_ID, LocalDateTime.now());
더즈가 말한 테스트 케이스에 대해서도 추가 작성하겠습니다.
테스트 환경에서는 챌린지가 5개여서 걸러지는 것으로 생각하고 했는데 테스트 메서드 내에서는 이를 알기 어렵겠네요.
챌린지가 5개 있다는 것을 명시하기 위해 챌린지 조회를 하고 조회된 챌린지로 사이클을 생성하여 메서드만 봐도 알 수 있도록 수정할게요. 추가로 페이징 관련 테스트도 작성하겠습니다.

2022-10-15 07:17 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +                .containsExactly("미라클 모닝", "오늘의 운동", "스모디 방문하기");
앗! 확인하지 못했네요 ㅠㅠ 쿼리문 확인하고 작성하겠습니다.
CycleRepository에서 jpql과 fetch join을 사용하면 되겠네요.

2022-10-15 09:41 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
> +    }
메서드 이름을 다시 한번 생각해 보면 좋을 것 같아요.

`ChallengingRecords`는 기본적으로 `List<Cycle>`을 받아서 생성되죠. 이 `Cycle`들이 Challenger일지 과거의 기록들일지는 모르는 거라고 생각해요.

2022-10-15 09:57 UTC, ldk980130 requested changes
남겨주신 의견과 리팩터링 잘 보았습니다.

크게 더 고칠 건 없는데 간단한 리뷰 더 남겼으니까 이것만 처리하면 approve하면 될 것 같아요!

2022-10-15 09:57 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
> +    }
메서드 이름을 다시 한번 생각해 보면 좋을 것 같아요.

`ChallengingRecords`는 기본적으로 `List<Cycle>`을 받아서 생성되죠. 이 `Cycle`들이 `Challenger`일지 과거의 기록들일지는 `ChallengingRecords`는 모를 거라고 생각해요.

진행 중이지 않은 `Cycle`들이 내부에 들어왔을 때 이 메서드는 이름과 하는 일이 맞지 않는 게 문제겠네요

2022-10-15 09:57 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +        Challenge JPA_공부 = fixture.챌린지_조회(JPA_공부_ID);
알고리즘 풀기와 JPA 공부는 아래에서 사용하지 않는 것 같아 반환하지 않아도 될 것 같아요!

2022-10-15 09:57 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +        fixture.사이클_생성_NOTHING(더즈_ID, 스모디_방문하기.getId(), LocalDateTime.now());
여러 상황 고려 💯

2022-10-15 09:57 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
>          return getChallengeTabResponses(challenges, member, challengingRecords);
동의는 합니다. Conroller가 같은 api에 대해 /auth까지 포함해서 코드가 많아지겠죠. 

한편으로는 ramdom이나 popular 같이 테이블의 칼럼이 아닌 다른 기준으로 정렬하는 로직은 api를 따로 나눴어야 했나 싶기도 하네요.

지금 이 구조가 한 메서드가 여러 분기를 처리한다는 것이 장점이 될 수도 있겠지만 다음의 단점도 있다고 생각해요.

`인기 로직이 변경되어도, 랜덤 로직이 변경 되어도, 그 외에 테이블 컬럼으로 조회하는 로직이 변경되어도 모두 이 메서드에 손을 대야 한다`

저도 깔끔한 설계 방법이 당장은 떠오르지는 않지만 현재는 토닉의 의견대로 가는 것도 나쁘지 않다고는 생각합니다.

(만약 참가자 수를 반정규화할 수 있다면 if문 없이 깔끔하게 처리될텐데 말이죠)

2022-10-16 08:26 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
> +    }
내부 로직을 보면 반드시 challengingRecord가 진행중이라는 것에 대한 로직이 없군요
외부에서 진행중인 사이클을 조회해서 넣어주는 것 때문에 문제가 발생하는 것 같아요.
저는 ChallengingRecords라는 객체의 책임이 도전중인 기록들을 가지고 있다 라는 것을 내재적으로 포함하고 있다고 생각했어요.
그래서 challengingRecord의 개수를 세주면 도전중인 사람들의 수라고 생각을 하긴 했는데 저희가  challengingRecord에 대한 정의를 다시 이야기해보면 좋을 것 같아요
- ChallengingRecord가 한 사람의 하나의 챌린지에 대한 기록 + 도전중인 챌린지인지 아니면 단지 하나의 챌린지에 대한 기록을 담는 곳인지

만약 도전중인 챌린지만 가능하다면 ChallengingRecord 객체를 생성할 때 이에 대한 로직으 포함되면 좋을 것 같아요. 아니라면
위 메서드에서 진행중인 ChallengingRecord 개수를 조회해서 정렬하는 방법도 있을 것 같네요.

2022-10-16 08:26 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
> +        Challenge JPA_공부 = fixture.챌린지_조회(JPA_공부_ID);
넵 수정하겠습니다!

2022-10-17 04:38 UTC, ldk980130 approved these changes
수고하셨습니다!

2022-10-17 04:44 UTC, merged