feat: (be) n대의 WAS에서 스케줄러 가동 여부 유연하게 결정 구현
woowacourse-teams/2022-smody pull request #561
Opened 2022-10-14 11:20 UTC by ldk980130

### 스케줄러 가동
`java -jar -Dspring.profiles.active=prod -Dbatch.schedule.enabled=true smody-0.0.1-SNAPSHOT.jar`

### 스케줄러 가동 X
`java -jar -Dspring.profiles.active=prod smody-0.0.1-SNAPSHOT.jar
`

### 구현 원리
![image](https://user-images.githubusercontent.com/78652144/195834751-24f63f9b-2fba-482f-8357-2c22c430fe86.png)

`batch.schedule.enabled=true`일 때만 스케줄러 빈이 등록되도록 구현
`batch.schedule.enabled` 값이 없으면 자동으로 스케줄러가 안돌도록 동작

2022-10-15 07:33 UTC, tonic523 requested changes
더즈 스케줄러 가동 여부를 너무 잘 구현해주셨네요!
크게 건드릴 부분은 없고 config 클래스의 패키지 위치 관련해서 피드백 올렸으니 확인 부탁드려요~

2022-10-15 07:33 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/push/WebPushSchedulerConfig.java
> +}
오 `ConditionalOnProperty` 라는 어노테이션으로 프로펄티 값을 토대로 빈을 등록할 지 안할 지 결정할 수 있는 로직이군요! 👍

이 클래스는 빈을 등록시켜주는 config 클래스인데 config 패키지로 옮기는 건 어떨까요?

2022-10-15 09:34 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/push/WebPushSchedulerConfig.java
> +}
반영하겠습니다~

2022-10-16 06:36 UTC, tonic523 approved these changes

2022-10-17 04:43 UTC, merged