feat: (fe) 우테코 팀프로젝트 이벤트 챌린지 페이지 구현
woowacourse-teams/2022-smody pull request #563
Opened 2022-10-14 13:01 UTC by wonsss

2022-10-15 10:59 UTC, wonsss commented
## Tabs 컴포넌트 구현하여 이벤트 페이지에 적용
- 다크모드 여부에 따른 Tabs 컴포넌트 스타일
![image](https://user-images.githubusercontent.com/59413128/195982845-a0f5d04e-00da-4b69-9cf0-18637701592c.png)
![image](https://user-images.githubusercontent.com/59413128/195982850-332e2330-93db-4bd6-bfec-5e10ba96d7c0.png)

2022-10-16 06:48 UTC, woose28 requested changes

2022-10-16 06:48 UTC, woose28 commented on frontend/src/pages/ChallengePage/index.tsx
> +
현재 NavBar 컴포넌트의 챌린지 버튼을 누르면 CLIENT_PATH.CHALLENGE router로 이동하게 됩니다!
따라서 해당 코드에 의해 CLIENT_PATH.CHALLENGE 일때 not fount가 렌더링됩니다~

NavBar에서 챌린지 버튼을 눌렀을 때 이동하는 url을 수정하거나 CLIENT_PATH.CHALLENGE 일 때 렌더링 되는 컨텐츠를 수정해야 할 거 같아요!

2022-10-16 07:23 UTC, wonsss commented on frontend/src/pages/ChallengePage/index.tsx
> +
challenge 라우터 삭제하는 방향으로 수정했습니다

2022-10-16 07:24 UTC, woose28 approved these changes
수정사항 확인했습니다~ 고생하셨어요!

2022-10-16 07:25 UTC, merged