feat: (fe) webpack 설정 리팩터링(babel-loader 적용 및 최적화 등)
woowacourse-teams/2022-smody pull request #634
Opened 2022-10-28 11:45 UTC by wonsss

- dev와 prod의 웹팩 설정 분리
- polyfill 사용을 위해 esbuild-loader를 제거하고 babel-loader 적용
    - 타입체킹을 하지 않고 esbuild-loader 사용할 당시 빌드 속도
    	- dev: 4초
    	- prod : 13초
- prod에 babel-loader 적용 후 트랜스파일링과 폴리필 적용(target: safari 11)
- prod에서 타입체킹( fork-ts-checker-webpack-plugin) 추가
	- 빌드 시, 38초 
		- (참고로 fork-ts 대신에 tsc로 타입체킹했을 때는 53초 소요되어 나은 점이 없다고 판단) 
- dev에서는 빌드 속도 향상을 위해 불필요한 최적화 옵션 등을 제거하고, 캐시를 적용
	- 첫 빌드 시, 13초
	- 리빌드 시, 2초
- prod에서 styled component의 최적화 적용
- dev에서 styled component 클래스명에 컴포넌트 이름을 표시
- babel-loader의 빌드 타임 측정 관련 플러그인 추가
	- SpeedMeasurePlugin, ProgressPlugin

2022-10-29 18:27 UTC, woose28 requested changes

2022-10-29 18:27 UTC, woose28 commented on frontend/webpack/webpack.prod.js
> +      new ForkTsCheckerWebpackPlugin(),
우리 빌드 전략은 development 환경일 때 type checking을 하는 걸로 알고 있습니다.
하지만, prod 환경에서 타입 확인하고 있네요! 특별한 이유가 있을까요ㅎㅎ?

2022-10-29 18:37 UTC, wonsss commented on frontend/webpack/webpack.prod.js
> +      new ForkTsCheckerWebpackPlugin(),
development 환경에서 웹팩 설정의 목표는 빠른 개발을 돕는 것입니다.
이를 위해 빌드와 리빌드 속도를 빠르게 해야 합니다.
그런데 타입체킹을 development 환경에서 빌드시 매번 하게 된다면, 타입체킹만으로 기본적으로 수십 초가 소요되어 이전에 캐시 및 최적화 등을 통해 얻은 빠른 빌드 속도 이점이 사라진다고 판단했습니다.

타입체킹은  개발 시 제한적이지만 vscode의 tsserver를 통해서도 실시간으로 확인할 수 있어 계속 팔로우할 수 있습니다. 그러다가 혹시나 놓친 타입에러는 production 빌드 시 적용해둔 ForkTsCheckerWebpackPlugin를 통해 확인할 수 있을 것입니다.

이처럼  development는 빠른 개발 속도, 그리고 production은 최종 코드 품질과 최적화 등에 신경 쓰는 것이 맞을 것 같습니다.

빅터 생각은 어떤가요?

2022-10-29 18:40 UTC, wonsss commented
본 PR 코드와 관련하여, 웹팩 설정에 대해 정리하였습니다.

https://wonsss.github.io/webpack/webpack-all-in-on

2022-10-29 19:08 UTC, woose28 commented on frontend/webpack/webpack.prod.js
> +      new ForkTsCheckerWebpackPlugin(),
> production은 최종 코드 품질과 최적화 등에 신경 쓰는 것이 맞을 것 같습니다.

동의합니다. 혹시나 급한 상황에서 코드를 수정하고 production으로 빌드하는 상황이 생긴다고 가정을 해봤습니다. 이런 경우에도 type 확인은 필요하니, 코드 품질을 위해 production에서 타입을 확인하는 절차도 필요하겠네요.

> 타입체킹은 개발 시 제한적이지만 vscode의 tsserver를 통해서도 실시간으로 확인할 수 있어 계속 팔로우할 수 있습니다.

맞습니다. tsserver로 타입을 실시간으로 확인할 수 있죠! 다시 생각해보니 개발단에서 타입 오류가 발생 곳은 대부분 경우 본인이 현재 작성 중인 파일이란 생각이 드네요. 그렇다면 tsserver로 대부분의 타입 에러를 확인할 수 있을 거 같아요.

production에서 type 확인하는 거로 가시죠!

2022-11-01 07:29 UTC, woose28 approved these changes
명확하게 이유를 설명해주셔서 감사합니다!! Approve할게요~!

2022-11-01 07:29 UTC, merged