feat: (be) 사이클 진척도 증가시 cycleDetailId 추가
woowacourse-teams/2022-smody pull request #645
Opened 2022-11-03 07:32 UTC by ldk980130

챌린지 인증 시 (피드 작성 시)에도 맨션을 하고 싶다는 요구가 들어왔어요. 기존에 있던 맨션 api를 사용하면 되는 문제지만 그러려면 pathId로 cycleDetailId가 필요합니다.

기존의 사이클 진척도 증가 api의 응답으로는 주고 있지 않던 정보라서 추가하기로 했습니다.
![image](https://user-images.githubusercontent.com/78652144/199666311-a54b4389-e585-4dc3-a796-52ef7c45ed20.png)
 
그래서 다음과 같이 반영했습니다.
![image](https://user-images.githubusercontent.com/78652144/199666756-04618038-1954-4180-a338-5db36851f29e.png)

### 문제 상황
그런데 이렇게 하니 cycleDetailId가 null인 현상이 발생했습니다. 일반적인 insert 문이라면 바로 SQL을 날려 id를 받아왔을 것입니다. 하지만 우리는 `CycleDetail`을 영속성 전이로 저장하고 있습니다. (`Cascade.PERSIST`) 영속성 전이로 발생한 저장은 `flush()` 시점에 쿼리가 날아가기 때문에 DTO를 세팅하는 저 시점은 `flush()` 전이라 id가 null인 것입니다.

### 해결 방법
강제적인 `flush()` 호출이 필요했습니다. 그런데 기존의 `CycleApiService`에서는 `EntityManager`나 `CycleRepository`가 없어 추가적인 의존이 필요한 상황입니다. 그래서 원래 `CycleRepository`를 가지고 있는 `CycleService`가 `flush()`를 해주도록 `increaseProgress()` 메서드를 `CycleService`가 하도록 변경했습니다.

![image](https://user-images.githubusercontent.com/78652144/199667570-3269585d-3d04-4ecc-9548-cbb28ab344ca.png)

![image](https://user-images.githubusercontent.com/78652144/199667545-97e5fd29-a393-42b1-b364-ecd4a05e10ae.png)

리뷰 잘 부탁드립니다!

2022-11-03 08:15 UTC, jojogreen91 requested changes
문제상황을 너무 잘 설명해주셔서 좋았고 말씀해주신 방법으로 구현도 문제없는거 같습니다!
다만 몇가지 궁금한 점이 있어서 남겼습니다 :)

2022-11-03 08:34 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
> +        cycleRepository.flush();
1. 저도 그런줄 알았는데 실제로 `flush()`를 호출해주지 않으면 id가 null로 세팅되어 있는 것을 확인했습니다. 추가적인 `flush()`는 필요한 상황입니다.
2. `REQUIRES_NEW` 도 방법이겠네요! 실제로 실험을 해보니 테스트는 다 통과하는 것을 확인했습니다. 그런데 이렇게 트랜잭션을 분리하면 커넥션을 하나 더 생성하는 것이 되어 한 스레드에서 두 커넥션을 물고 있게 될 것 같습니다. 어떤게 더 좋은 방법일까요?

2022-11-03 09:05 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
> +        cycleRepository.flush();
아 그러네요 트랜잭션이 분리 되면서 케넥션이 하나 더 생겨버리네요.
근데 지금 increaseProgress 하는 상황에 대해서만 봤을 때는 ApiService 쪽의 트랜잭션을 오히려 제거해 줘도 되지 않을까요?
ApiService 쪽 메서드에서 하는 일이
Service 메서드 호출 + 이벤트 생성인데
이벤트는 저희가 현재 비동기 방식으로 처리하고 있어서 ApiService 쪽의 트랜잭션을 오히려 제거하는것도 괜찮을거 같은데 어떻게 생각하시나요?

2022-11-03 09:54 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
> +        cycleRepository.flush();
트랜잭션을 제거하자 알림 로직이 실행이 안되네요. 아마 TransactionalEventListener가 커밋 후에 동작하는 친구라 이벤트를 퍼블리싱하는 ApiService에 트랜잭션이 없으니 알림이 저장 안되는 듯 해요.

2022-11-03 20:49 UTC, jojogreen91 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
> +        cycleRepository.flush();
아하 그렇겠네요.
그렇다고 트랜잭션 이벤트 리스너가 아니라 그냥 이벤트 리스너를 사용할 수도 없고...
뭔가 아쉽네요. 다른 방법이 없을까요...

2022-11-04 01:47 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
> +        cycleRepository.flush();
어떤 방법을 써도 조금씩 어색해질 것 같은데 그나마 가장 깔끔한 방법이 flush()인 것 같긴 해요ㅋㅋㅋㅋ 이대로 가는 건 어떠실까요?

2022-11-04 01:49 UTC, merged