refactor: (be) 챌린지 탭 조회 로직 개선
woowacourse-teams/2022-smody pull request #671
Opened 2023-01-30 15:45 UTC by tonic523

#670
## 목표
- 챌린지 탭 조회의 복잡한 로직을 개선
- 탭 별로 조회하는 로직을 객체로 분리한다.
- ChallengeApiService는 탭 별 조회 로직에 대해서 의존하지 않는다.

## 구현한 기능
- [x] `ChallengeSort` : 요청한 데이터에 맞게 정렬된 챌린지를 조회한다.
  - 이 때 발생한 쿼리를 토대로 참가자 수를 저장한다.
  - [x] `Default` : 검색 및 기본 조회 로직을 담당한다.
  - [x] `Popular` : 참가자 순 조회 로직을 담당한다.
  - [x] `Random` : 추천(랜덤) 조회 로직을 담당한다.
- [ ] `ChallengingRecords` : 조회에서 발생한 쿼리를 토대로 기록한다.
  - [ ] 테스트 구현

## 개선할 부분
- `sort` 정렬 기준이 없을 경우 발생하는 분기 처리를 개선하고 싶다.

---

빈 `ChallengingRecords`를 생성하고 이 후에 기록하는 방식은 어떤가요? 추상화를 위해 구현했지만, 기록한다는 이름이 클래스에 있는 것 처럼 활용해도 어색하지 않다고 생각이 듭니다. 다른 곳에서도 위 처럼 적용해보면 오히려 이전의 `from()` 로직보다 이해하기 좋은 코드라고 생각이 들어요.
- `from(List<Cycle>)` -> `record(List<Cycle>)`

피드백 주시면 적극 반영하도록 하겠습니다 ㅎㅎ 개선할 부분에 대해서 의견을 주시면 너무 고마울 것 같아요!

2023-01-31 06:10 UTC, ldk980130 requested changes
토닉 오랜만에 코드 리뷰네요~ 리팩터링 해주신거 잘 봤습니다. 확실히 if문으로 복잡했던 예전 코드보다 지금이 훨씬 읽기 좋은 것 같아요. 정렬에 관한 로직을 추상화해서 Service 계층이 훨씬 깔끔해진 것 같습니다. 게다가 특정 정렬 규칙을 한 파일에서만 볼 수 있으니 개인적으로 더 파악하기 쉬운 것 같아요. 네이밍 관련한  간단한 리뷰 남겼는데 확인해주세요!

2023-01-31 06:10 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
> +            sort = "default";
sort를 String으로 관리하고 있는데 이것도 Enum으로 관리하면 좋지 않을까요?

2023-01-31 06:10 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
> +    private final Map<String, ChallengeSort> sortHandler;
이렇게만 선언해도 모든 빈이 Map에 주입되는군요! 키값은 빈의 이름이 되는거죠?

2023-01-31 06:10 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/sort/Default.java
> +public class Default implements ChallengeSort {
구현체 이름만 봤을 때는 무슨 `Default`인지 알 수가 없는 것 같아요. `Popular`랑 `Random`도 마찬가지인데 `DefaultChallengeSortHandler`, `PopularChallengeSortHandler`, `RandomChallengeSortHandler`로 구현체 이름을 바꾸는 것은 어떨까요?

2023-01-31 06:10 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/sort/ChallengeSort.java
> +public interface ChallengeSort {
이 인터페이스를 사용하는 클라이언트 코드에선 변수 이름을 `sortHandler`로 사용하고 있던데 이 이름이 더 좋은 것 같아요. `ChallengeSortHandler`라는 이름은 어떨까요?

2023-01-31 06:22 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
> +    private final Map<String, ChallengeSort> sortHandler;
네! 현재는 클래스 이름이 빈 이름으로 설정되어서 자동으로 주입됩니다.

2023-01-31 06:23 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/sort/Default.java
> +public class Default implements ChallengeSort {
구체적으로 네이밍하는게 이해하기 더 좋겠네요! 수정하겠습니다.

2023-01-31 06:23 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/sort/ChallengeSort.java
> +public interface ChallengeSort {
넵! 반영하겠습니다

2023-01-31 08:45 UTC, tonic523 commented
역시 더즈! 빠른 피드백 감사드려요 ㅎㅎ
피드백 덕분에 아이디어가 떠올라 더 좋은 개선 방안으로 찾아뵙습니다!

## Enum으로 구현했을 때 문제점
```java
public enum ChallengeSortHandlerKey {

    DEFAULT_CHALLENGE_SORT_HANDLER("", "defaultChallengeSortHandler"),
    POPULAR_CHALLENGE_SORT_HANDLER("popular", "popularChallengeSortHandler"),
    RANDOM_CHALLENGE_SORT_HANDLER("random", "randomChallengeSortHandler")
    ;

    private final String pagingParamsSortValue;
    private final String beanName;

    ChallengeSortHandlerKey(String pagingParamsSortValue, String beanName) {
        this.pagingParamsSortValue = pagingParamsSortValue;
        this.beanName = beanName;
    }

    public static String getBeanName(String pagingParamsSortValue) {
        return Arrays.stream(values())
                .filter(item -> item.pagingParamsSortValue.equals(pagingParamsSortValue))
                .findAny()
                .orElse(DEFAULT_CHALLENGE_SORT_HANDLER)
                .beanName;
    }
}
```
저는 enum으로 스프링 빈 이름과 쿼리파라미터의 값을 매핑하는 구조로 구현했는데요. 이렇게 구현하다보니 추가되는 정렬 기준이 있을 때 마다 enum에 있는 매핑되는 값을 구현해야 하는 구조가 됐어요. 개발자가 실수할 수 있는 부분이라고 생각해서 스프링 MVC 구조 중 `HandlerMapping` 의 객체를 구현해보았어요.

```java
@Component
@RequiredArgsConstructor
public class ChallengeSortHandlerMapping {

    private final List<ChallengeSortHandler> challengeSortHandlers;
    private final DefaultChallengeSortHandler defaultChallengeSortHandler;

    public ChallengeSortHandler getHandler(String pagingParamsSortValue) {
        return challengeSortHandlers.stream()
                .filter(challengeSortHandlerHandler -> challengeSortHandlerHandler.getSortValue()
                        .equals(pagingParamsSortValue))
                .findAny()
                .orElse(defaultChallengeSortHandler);
    }
}
```

이 때 매핑할 기준을 정하기 위해 `ChallengeSortHandler`에 메서드를 추가했습니다.
- `getSortValue()`: 쿼리파라미터로 매핑할 값을 반환
```java
public interface ChallengeSortHandler {

    List<Challenge> handle(LocalDateTime searchTime, PagingParams pagingParams,
                           ChallengingRecords challengingRecords);

    String getSortValue();
}
```

한 번 보시고 의견주시면 감사하겠습니다!

2023-01-31 13:34 UTC, ldk980130 approved these changes
토닉 리뷰 반영 수고하셨습니다! `MapTest`는 학습 테스트 목적으로 만드신 것 같은데 꼭 필요한 테스트는 아닌 것 같아서 지우면 좋을 것 같다는 의견만 남겼습니다. 나머지는 깔끔한 것 같아요. 리팩터링 수고하셨습니다~

2023-01-31 13:34 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
> +        ChallengeSortHandler handler = challengeSortHandlerMapping.getHandler(pagingParams.getSort());
스프링 MVC에서 영감을 얻은 구조군요ㅋㅋㅋㅋ 확실히 깔끔해진 것 같습니다.

2023-01-31 13:34 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/MapTest.java
> +}
이 테스트는 남겨둘 필요는 있을까요? 확인했으니 지워도 좋을 것 같아요!

2023-02-01 13:30 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/MapTest.java
> +}
아 깜빡했네요.. ㅎㅎ 수정할게요

2023-02-02 15:39 UTC, merged