refactor:(be) 사이클 생성 로직 도메인 영역에서 구현하도록 변경
woowacourse-teams/2022-smody pull request #672
Opened 2023-02-07 13:00 UTC by ldk980130

오랜만에 PR 드립니다! 복잡한건 아니고 최근에 DDD를 공부하는 김에 간단한 변경 사항 한 번 적용해 보았습니다. 목적은 도메인 로직을 도메인 영역으로 밀어넣어 도메인 응집도를 높이기 위함입니다.

## 이전의 사이클 생성 로직
``` java
    @Transactional
    public Cycle create(Long memberId, Long challengeId, LocalDateTime startTime) {
        Member member = memberService.search(memberId);
        Challenge challenge = challengeService.search(challengeId);
        Optional<Cycle> optionalCycle = cycleRepository.findRecent(member.getId(), challenge.getId());
        if (optionalCycle.isPresent()) {
            startTime = calculateNewStartTime(startTime, optionalCycle.get());
        }
        return cycleRepository.save(new Cycle(member, challenge, Progress.NOTHING, startTime));
    }

    private LocalDateTime calculateNewStartTime(LocalDateTime startTime, Cycle cycle) {
        if (cycle.isInProgress(startTime)) {
            throw new BusinessException(ExceptionData.DUPLICATE_IN_PROGRESS_CHALLENGE);
        }
        if (isRetry(startTime, cycle)) {
            return cycle.getStartTime().plusDays(Cycle.DAYS);
        }
        return startTime;
    }

    private boolean isRetry(final LocalDateTime startTime, final Cycle cycle) {
        return cycle.isSuccess() && cycle.isInDays(startTime);
    }
```
사이클을 생성하는 로직은 도메인 로직입니다. 하지만 다른 사이클의 존재 유무 때문에 생성할 수 있냐 없냐가 결정되는 규칙 때문에 리포지터리를 이용하고자  애플리케이션 영역(서비스 레이어)에 도메인 로직이 삐져나와 있습니다. 사이클 생성에 대한 업무 규칙이 여러 레이어(패키지)에 분산되어 있어 응집도가 떨어지고 사이클 생성 로직이 변경된다면 도메인 패키지도, 서비스 패키지도 수정해야 하는 불편함이 있습니다.

## 도메인 영역에서 팩토리를 통해 사이클 생성
``` java
    @Transactional
    public Cycle create(Long memberId, Long challengeId, LocalDateTime startTime) {
        Member member = memberService.search(memberId);
        Challenge challenge = challengeService.search(challengeId);
        return CycleFactory.create(member, challenge, startTime, cycleRepository);
    }
```
사이클을 생성하는 팩토리 클래스에 사이클 생성 책임을 위임했습니다. `CycleFactory`는 도메인 영역에 위치하고 있기에 도메인 영역에 해당합니다. 서비스 레이어 흩어져 있던 사이클 도메인 규칙을 도메인 영역으로 넣어 응집도를 높였습니다. 사이클 생성에 관해 변경이 생긴다면 도메인 영역(패키지)만 수정하면 됩니다.

## 리포지터리를 파라미터로 전달?
사이클 생성에 관한 업무 규칙을 구현하기 위해선 사이클 저장소에 접근할 필요가 있었기에 `CycleRepository`가 필요했습니다. 처음엔 `CycleFactory`를 빈으로 만들어 리포지터리를 DI 받을까 생각도 했었습니다. 하지만 그렇게되면 도메인 영역인 `CycleFactory`를 테스트 하기 위해 스프링 컨테이너를 띄워야 했기에 인터페이스를 파라미터로 전달 받는 쪽으로 구현했습니다. 

## CycleRepository 패키지 
원래 저희 팀 컨벤션으론 리포지터리 인터페이스의 위치는 `repository` 패키지에 위치합니다. 하지만 점진적으로 리포지터리 인터페이스들을 도메인 영역에 넣고 싶다는 생각을 하고 있습니다. 도메인 저장소인 리포지터리는 도메인 패키지로, 그것을 구현한 클래스는 `repository` 패키지에 위치시키는 것입니다. 우선 `Cycle` 패키지에선 리포지터리 인터페이스를 도메인 영역에 위치시켜 놓았습니다.

2023-02-07 15:52 UTC, tonic523 requested changes
안녕하세요 더즈!
오랜만에 코드리뷰하면서 좋은 설계에 대해 고민할 수 있었고 DDD에 대해서 알아가고 싶어졌어요! ㅎㅎ
간단한 수정 관련 리뷰를 빼고는 더즈와 의견을 나누고 싶은 부분들을 코멘트로 남겼습니다.

인터페이스의 위치 관련해서 점진적으로 바꾸고 싶다고 하셨는데 일관성있는 컨벤션을 정하면 좋을 것 같아요!
1. 서비스에 repository(저장소)에 의존한 도메인 로직이 있는 경우 domain 패키지에 repository 인터페이스를 옮긴다.
2. 전체적으로 인터페이스를 의존하는 패키지에 인터페이스를 옮긴다.

2번이라면 인터페이스를 의존하는 패키지가 2군데 이상일 경우는 어떻게 해아할지 더즈의 생각이 궁금합니다!

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleFactoryTest.java
> +    @DisplayName("현재 시각 기준 24시간이 이후가 지난 시작시간을 가진 사이클을 생성할 때 예외를 발생시킨다.")
```suggestion
    @DisplayName("현재 시각 기준 24시간이 지난 시작시간을 가진 사이클을 생성할 때 예외를 발생시킨다.")
```
어순이 조금 어색한 것 같아서 위 처럼 바꾸는 것은 어떤가요?

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +package com.woowacourse.smody.cycle.domain;
인터페이스를 의존하고 있는 곳에서 인터페이스를 가지니 패키지 간 의존관계가 없어지네요! 덕분에 domain과 repository 패키지 간의 순환참조가 발생하지 않네요. 앗 다시 보니 `CycleRepository` 에서 repository 패키지를 참조하긴 하네요! 이정도도 충분히 괜찮다고 생각이 드는데 패키지 간 순환 참조를 개선할 수 있다면 아래 방법도 있을 것 같습니다.
- 도메인에서 사용하는 메서드를 기준으로 인터페이스 구현
- 해당 인터페이스의 구현체는 repository에서 구현
- 구현체에 대한 의존 주입은 스프링 컨테이너에게 위임

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleFactoryTest.java
> +    private CycleRepository cycleRepository;
테스트를 Mock과 함께 꼼꼼하게 잘 구현해주셨네요 ㅎㅎ
현재 `CycleFactory` 가 파라미터로 `CycleRepository`를 받는 형식으로 되어있습니다. 더즈가 우려했던 점은 테스트를 작성할 때 스프링 컨테이너를 띄워야 하는 성능 문제였는데요. 이 부분은 스프링 컨테이너의 의존 주입으로 생성하는 빈을 테스트 내에서는 직접 인스턴스를 생성해서 사용하여 해결할 수 있을 것 같아요.
```java
    @Mock
    private CycleRepository cycleRepository;

    @DisplayName("사이클을 생성한다.")
    @Test
    void create() {
        // given
        given(member.getId()).willReturn(조조그린_ID);
        given(challenge.getId()).willReturn(미라클_모닝_ID);
        given(cycleRepository.findRecent(조조그린_ID, 미라클_모닝_ID))
                .willReturn(Optional.empty());

        CycleFactory cycleFactory = new CycleFactory(cycleRepository);
        LocalDateTime startTime = LocalDateTime.now();

        // when
        Cycle actual = cycleFactory.create(member, challenge, startTime);

        // then
        assertThat(actual.getStartTime()).isEqualTo(startTime);
    }
```
service 계층에서 domain으로 repository를 파라미터로 넘기는 부분이 어색하다고 느껴지기도 하고 스프링의 di 이점을 살려서 파라미터를 줄이는 방향이 더 괜찮아보이는 것 같습니다! 이렇게 수정해보는건 어떤가요?

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +package com.woowacourse.smody.cycle.domain;
추가로 `cycleRepository.deleteByMember(Member member)` 는 사용하지 않는 메서드인 것 같아요 저번 회원탈퇴로직을 cascade 처리로 바꾸면서 필요없어진 메서드 같습니다 ㅎㅎ

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleFactory.java
> +        }
```suggestion
        if (cycle.isRetry(startTime)) {
            return cycle.getRetryStartTime();
        }
```
메서드로 로직을 감싸서 캡슐화하면 좋을 것 같아요!

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
>  import com.woowacourse.smody.cycle.domain.Cycle;
```suggestion

```
안쓰이는 import문이네요!

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
> +        return CycleFactory.create(member, challenge, startTime, cycleRepository);
도메인으로 로직을 옮겨 깔끔해졌네요 ㅎㅎ

2023-02-07 15:52 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleFactoryTest.java
> +}
```suggestion
}

```

2023-02-08 06:31 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleFactoryTest.java
> +    @DisplayName("현재 시각 기준 24시간이 이후가 지난 시작시간을 가진 사이클을 생성할 때 예외를 발생시킨다.")
반영하겠습니다~!

2023-02-08 06:57 UTC, ldk980130 commented on backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleFactoryTest.java
> +    private CycleRepository cycleRepository;
다시 생각해보니 생성자 주입 받는 방식으로 가도 될 것 같네요. 대신 `CycleFactory` 클래스를 `@Component`나 따로 Config 클래스로 빈으로 만들지 않고 아래와 같이 `CycleService` 생성자에서 수동으로 생성하였습니다.
```
    public CycleService(CycleRepository cycleRepository,
                        CycleDetailRepository cycleDetailRepository,
                        MemberService memberService,
                        ChallengeService challengeService) {
        this.cycleRepository = cycleRepository;
        this.cycleDetailRepository = cycleDetailRepository;
        this.memberService = memberService;
        this.challengeService = challengeService;
        this.cycleFactory = new CycleFactory(cycleRepository);
    }
```
도메인 영역인 `CycleFactory`에 빈 등록 스프링 관련 코드도 넣지 않아도 되고 따로 Config 클래스를 만들어 빈 등록하지 않아도 위와 같이 하면 싱글턴처럼 쓸 수 있습니다

2023-02-08 07:13 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +package com.woowacourse.smody.cycle.domain;
사용하지 않는 `deleteByMember`는 삭제했습니다!

2023-02-08 07:17 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +package com.woowacourse.smody.cycle.domain;
> CycleRepository 에서 repository 패키지를 참조하긴 하네요

저희가 정의한 repository 패키지로의 참조는 없습니다. 아마 스프링의 repository를 잘못 보신걸까요?
`import org.springframework.data.repository.query.Param;`

그리고 `repository`의 위치를 도메인 영역으로 옮기려는 이유는 패키지 순환 참조도 있겠지만 DIP 때문이기도 합니다. `CycleFactory`를 사용하게 되면 도메인 영역에서 리포지터리를 의존하게 되는데 리포지터리 위치가 `repository`이기 때문에 `domain -> repository`의 의존 방향이 생깁니다. 도메인 영역이 보통 세부 사항인 인프라 영역에 의존하는 것을 좋은 설계라고 보지 않기 때문에 의존 방향을 역전시키기 위해 인터페이스는 도메인 영역으로 옮긴 것입니다. 비단 DBMS 뿐만 아니라 다양한 인프라 영역을 사용하는 도메인 로직을 이처럼 의존성을 역전시킬 수 있습니다

2023-02-08 15:40 UTC, tonic523 requested changes
더즈 빠르게 반영해주셨군요!
import 관련 패키지 의존 부분만 이야기해보면 될 것 같아요!

2023-02-08 15:40 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +package com.woowacourse.smody.cycle.domain;
DIP를 지키기 위해서도 있었군요! 하나 또 배워가네요 ㅎㅎ 

Import 관련해서는 밑에 추가 리뷰 확인부탁드릴게요.

2023-02-08 15:40 UTC, tonic523 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +import com.woowacourse.smody.cycle.repository.DynamicCycleRepository;
이 부분을 말씀드린거였습니다. `CycleRepository` 에서 `DynamicCycleRepository` 인터페이스를 상속하면서 `repository` 패키지를 의존하고 있네요. 또한 spring.data.jpa도 의존하는데 이 2가지 의존도 도메인내에서만 사용하는 인터페이스로 분리하여 끊어낼 수 있지 않을까요?
```java
public interface CycleDomainRepository {

    Optional<Cycle> findRecent(Long memberId, Long challengeId);

    Cycle save(Cycle cycle);
}
```
만약 `CycleRepository` 즉 Cycle 저장소가 domain의 역할이고 구현체를 `repository` 패키지로 분리했다! 라면 현재 코드도 좋습니다. 만약 이런 코드로 가게 된다면 다른 모든 패키지도 위 처럼 수정해야겠죠. 더즈가 구현한 의도가 이게 맞을까요?

2023-02-08 15:40 UTC, tonic523 commented on backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/CycleFactoryTest.java
> +    private CycleRepository cycleRepository;
오 이것도 괜찮은 방법 같네요. 싱글턴처럼 사용할 수 있다면 굳이 스프링 관련 코드를 추가하지 않아도 될 것 같아요!

2023-02-09 07:21 UTC, ldk980130 commented on backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleRepository.java
> +import com.woowacourse.smody.cycle.repository.DynamicCycleRepository;
그렇네요. 복잡한 조회를 위한 `DynamicCycleRepository`를 같이 구현하고 있었네요.

`CycleRepository`를 **도메인 로직을 위한 저장소라고 정의**한 이상 복잡한 조회 때문에 필요했던 동적 쿼리가 함께 있는 것도 다시 보니 많은 책임을 가진 것 같긴 해요. 그래서 이 둘을 분리하면 어떨까요? 
``` java
@Service
@Transactional(readOnly = true)
public class CycleService {

    private final CycleRepository cycleRepository;
    private final DynamicCycleRepository dynamicCycleRepository;

}
```
두 리포지터리를 분리하면 우려했던 의존은 사라집니다. 

## 도메인에서 spring.data.jpa를 의존
DDD 책에도 비슷한 내용이 나와요. 인터페이스를 통한 DIP로 `도메인 -> 인프라에 의존`을 걷어냈는데 도메인쪽에 JPA 관련 애너테이션이 덕지덕지인건 DIP를 위반한 것 아니냐고요. 사실 인프라를 의존하지 않고 의존을 역전시키는건 인프라 영역은 세부 구현 사항이라 언제든지 바뀔 수 있기 때문이에요. 나중에 DBMS만으로 성능이 안나와서 리포지터리를 캐시나 NoSQL로 변환할 때 도메인, 서비스 계층엔 영향을 최소화하기 위해서가 예시 중 하나죠.

하지만 복잡한 조회가 아닌 업무 규칙과 관련된 로직은 JPA와 Spring Data JPA를 사용하는 경우가 많고 잘 안바뀔거에요. (도메인 주도 개발 시작하기의 저자 범균님도 거의 바뀌는걸 못보셨다고 했음) **유연한 설계**도 물론 중요하지만 **구현의 편함**도 유지보수에서 무시할 수 없는 요소에요. 엔티티에서 JPA 애너테이션을 제거하면 엔티티와 JPA를 매핑하는 복잡한 외부 처리를 해줘야 하죠. 이는 거의 바뀔 가능성 없는 JPA 기술에 한에서는 생산성의 낭비라고 생각하는거죠.

DIP와 구현의 용이성 그 둘 사이의 밸런스를 잘 맞춰가는 것이 중요한데 그런 차원에서 스프링이나 JPA 관련 설정이 도메인에 조금 스며드는 것은 거의 바뀔 일 없는 사항에 구현의 용이성을 챙겨가는거라 괜찮다고 생각했습니다!

## 점진적인 조회 분리 리팩터링
제가 예전에 말했던 복잡한 조회를 아예 다른 곳으로(패키지) 분리하고 싶다는 것 기억하시나요? 객체지향적으로 온전히 설계하고 싶은 명령 모델과 UI에 맞춰 필요한 정보를 복잡하게 조회해야 하는 쿼리지향, 절차지향적인 공간을 분리하는 쪽으로 점지적으로 리팩터링하고 싶어요. 그럼 `CycleRepository`에 정말 필요한 도메인 로직만 남게 될거에요.

이 PR이 머지되면 그 분리를 한 번 진행해보고 싶어요.

2023-02-09 09:19 UTC, tonic523 approved these changes
더즈가 리팩토링하고 싶은 의도도 이해했고 리팩토링을 잘 수행해주셔서 merge해도 될 것 같아요 ㅎㅎ
- 도메인에서 jpa에 관련한 의존 역시 저도 같은 생각입니다. 만약 Jpa 를 사용하지 않게 되더라도 인터페이스로 구현되어 있어 괜찮다고 생각합니다.
---
> 점진적인 조회 분리 리팩터링

앞으로 점진적으로 복잡한 조회와 설계하고 싶은 명령 모델을 분리하고 싶다고 하셨어요. 이 부분을 저도 공감합니다. 단, 여기서 `복잡하다`와 객체지향적으로 온전히 설계하고 싶은 `명령 모델`에 대해서 팀원들과 같이 정의를 해봐야할 것 같다는 생각이 듭니다. 팀원들마다 `명령 모델`과 `복잡하다`의 기준이 다를 수 있다고 생각이 들어요. 리팩토링 작업을 하시게 되시면 `복잡하다`와 `명령 모델` 에 대한 기준에 대해서 공유해주시면 좋을 것 같습니다!
## 명령 모델
- 도메인 내에서 사용하는 CRUD 쿼리의 인터페이스(현재 `CycleRepository`는 도매인 이외에도 다른 Service에서 사용하는 인터페이스를 제공하고 있어요.)
- Cycle 저장소

## 복잡한 조회
- PagingParams에 따라 동적으로 바뀌는 조회

제가 지금 생각나는 기준은 다음과 같은데 나중에라도 더즈가 생각하는 기준을 공유해주시거나 같이 이야기해보면 좋을 것 같습니다! 리팩토링하느라 고생많으셨어요~

2023-02-11 05:07 UTC, merged